# This config file is used for rerunning mPower Analysis for the Nature Biotech Submission
# it contains the required synapse ID output to replicate the paper and for the public release dataset 
# Maintainer: aryton.tediarjo@sagebase.org
default:
  git:
    path: "~/git_token.txt"
    repo: "Sage-Bionetworks/mPowerRerun"
    branch: "main"
  output:
    project_id: "syn26282646"
  additional:
    voice_features: 'syn22041873' #generated voice features from matlab (not reproducible)
public:
  metadata:
    user_group: 'public_release' # annotation helper for referring which user group
  output:
    folder_name: "mPower Rerun Results - Public"
    file_view_name: "mPower Rerun - Public - File View"
  synapse_tables:
    demo: "syn5511429"
    gait: "syn5511449" #walk and balance test 
    tap: "syn5511439"
    voice: "syn5511444"
  additional:
    utc_info: 'syn26450848'
6_months_study:
  metadata:
    user_group: '6_months_study' # annotation helper for referring which user group
  output:
    folder_name: "mPower Rerun Results - 6 Months Study"
    file_view_name: "mPower Rerun - 6 Months Study - File View"
  synapse_tables:
    demo: "syn7222419"
    gait: "syn7222425" #walk and balance test 
    tap: "syn7222423"
    voice: "syn7222424"
  additional:
    utc_info: 'syn23512320'
